name=input("pls enter your name: ")
surname=input("please enter your surname: ")
age=int(input("please enter your age: "))
Home_address=input("please enter your home address:")
Height=int(input("please enter your height "))
birth_date=int(input("please enter your birth date: "))